# This is a basic workflow to help you get started with Actions

name: Parent
# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: '*/2 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  All-Prequisite-Task1:
    # The type of runner that the job will run on
    runs-on: windows-latest
    #environment: BYPOC_Test

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Generate Environment Var
        env:
            CronVar: 'Now'
