# This is a basic workflow to help you get started with Actions

name: Parent
# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: '*/2 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my_job_1:
    runs-on: windows-latest
    steps:
      - name: Job 1
        run: echo first function!

  my_job_2:
    runs-on: windows-latest
    needs: [my_job_1]
    steps:
      - name: Job 2
      - uses: ./.github/workflows/PreFailoverValidation.yml
