# This is a basic workflow to help you get started with Actions

name: Parent
# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: '*/2 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my_job_1:
    runs-on: windows-latest
    steps:
    - uses: ./.github/workflows/PreFailoverValidation.yml
