# This is a basic workflow to help you get started with Actions

name: Parent
# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: '*/2 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build:
      env:
        vary: '11'
      name: Run Script
      runs-on: windows-latest
      steps:
        - name: Script
          run: |
           if [ '${{env.vary}}' == '11' ]; then
           echo "This is a validated"
           else
           echo "This is an unknown event"
