# This is a basic workflow to help you get started with Actions

name: Parent
# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: '*/2 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build:
      env:
        vary: 'Now'
      name: Run Script
      runs-on: windows-latest
      steps:
        - name: CheckOut Step
          uses: actions/checkout@v4          
        
        - name: Trigger Next WorkFlow
          if: ${{ env.vary == 'Now'  }}
          uses: ./.github/workflows/PreFailoverValidation.yml@main
          
