# This is a basic workflow to help you get started with Actions

name: Parent
# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: '*/2 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Parent-job-1:
    runs-on: windows-latest
    steps:
      - name: Job 1
        run: echo first function!

  Invoke-Prerequisite-WorkFlowcall:
    needs: [Parent-job-1]
    uses: ./.github/workflows/Prerequisite.yml
